"use client";

import { useToken } from "@/hooks/useToken";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { LiveKitRoom } from "@livekit/components-react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const token = useToken({});

  if (token === "") {
    return <div>Getting token...</div>;
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <LiveKitRoom
          video={true}
          audio={true}
          token={token}
          serverUrl={process.env.NEXT_PUBLIC_LIVEKIT_URL}
        >
          {children}
        </LiveKitRoom>
      </body>
    </html>
  );
}
